#更新refresh_token
name: update refresh_token

on: 
  release:
    types: [published]
  push:
    tags:
    - 'v*'
  #  branches: 
  #    - master
  schedule:
    - cron: '45 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.9

    - name: Install requests
      run: |
        pip install requests

    - name: Read config from secrets
      env: 
        ID_LIST: ${{ secrets.ID_LIST }}
        KEY_LIST: ${{ secrets.KEY_LIST }}
        ID_LIST2: ${{ secrets.ID_LIST2 }}
        KEY_LIST2: ${{ secrets.KEY_LIST2 }}
      run: |
        cp updatetoken.py updatetoken2.py
        echo $ID_LIST > idlist.txt
        echo $KEY_LIST > keylist.txt
        sed -i '10 r idlist.txt' updatetoken2.py
        sed -i '11 r keylist.txt' updatetoken2.py
        echo $ID_LIST2 > idlist2.txt
        echo $KEY_LIST2 > keylist2.txt
        sed -i '12 r idlist2.txt' updatetoken2.py
        sed -i '13 r keylist2.txt' updatetoken2.py

    - name: Pull latest changes from remote
      run: |
        git fetch origin
        git pull origin main

    - name: Update token
      run: |
        python updatetoken2.py

    - name: Delete secrets config
      run: |
        rm -f updatetoken2.py idlist.txt keylist.txt idlist2.txt keylist2.txt

    - name: Commit changes
      run: |
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git diff --exit-code || git commit -a -m "update new refresh_token"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
